"""
Main script for running LLM-Meta-SR on toy problems
"""
import numpy as np
from openai import OpenAI
import os
from typing import List, Dict, Tuple
import json
from toy_datasets import get_all_toy_datasets
from symbolic_regression import symbolic_regression
from meta_evolution import (
    SelectionOperator,
    semantics_aware_selection,
    multi_objective_survival_selection,
    generate_initial_operator,
    mutate_operator,
    crossover_operators
)

def evaluate_operator_on_dataset(operator: SelectionOperator, X, y, n_runs=3) -> float:
    """
    Evaluate a selection operator on a dataset

    Returns the average R^2 score across multiple runs
    """
    scores = []

    for run in range(n_runs):
        try:
            # Split into train/val
            n_samples = len(y)
            n_train = int(0.8 * n_samples)

            indices = np.random.permutation(n_samples)
            train_idx = indices[:n_train]
            val_idx = indices[n_train:]

            X_train, y_train = X[train_idx], y[train_idx]
            X_val, y_val = X[val_idx], y[val_idx]

            # Run symbolic regression
            best_ind, history = symbolic_regression(
                X_train, y_train,
                selection_operator=operator,
                pop_size=50,  # Smaller for speed
                n_generations=20,  # Fewer generations for speed
                crossover_rate=0.9,
                mutation_rate=0.1
            )

            # Evaluate on validation set
            y_pred = best_ind.evaluate(X_val)
            y_pred = np.clip(y_pred, -1e10, 1e10)

            # Compute R^2 score
            ss_res = np.sum((y_val - y_pred) ** 2)
            ss_tot = np.sum((y_val - np.mean(y_val)) ** 2)
            r2 = 1 - (ss_res / (ss_tot + 1e-10))

            scores.append(r2)
        except Exception as e:
            print(f"Error evaluating operator: {e}")
            scores.append(-1.0)  # Penalty for errors

    return np.mean(scores)


def evaluate_operator_on_all_datasets(operator: SelectionOperator, datasets: Dict) -> Tuple[float, List[float]]:
    """
    Evaluate operator on all datasets

    Returns:
        average_score: Average R^2 across all datasets
        score_vector: R^2 score for each dataset
    """
    scores = []

    for dataset_name, (X, y, formula) in datasets.items():
        print(f"  Evaluating on {dataset_name}...")
        score = evaluate_operator_on_dataset(operator, X, y, n_runs=2)
        scores.append(score)
        print(f"    Score: {score:.4f}")

    average_score = np.mean(scores)
    return average_score, scores


def run_meta_evolution(
    n_generations=10,
    population_size=10,
    n_crossover=7,
    n_mutation=1,
):
    """
    Run the meta-evolution loop

    Args:
        n_generations: Number of meta-evolution generations
        population_size: Number of selection operators in population
        n_crossover: Number of offspring generated by crossover
        n_mutation: Number of offspring generated by mutation
    """
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=os.getenv("OPENROUTER_API_KEY")
    )

    # Load toy datasets
    datasets = get_all_toy_datasets()
    print(f"Loaded {len(datasets)} toy datasets")
    print(f"Datasets: {list(datasets.keys())}")

    # Initialize population
    print("\n=== Initializing Population ===")
    population = []

    for i in range(population_size):
        print(f"Generating initial operator {i+1}/{population_size}...")
        try:
            code = generate_initial_operator(client)
            operator = SelectionOperator(code)

            # Evaluate on datasets
            print(f"Evaluating operator {i+1}...")
            avg_score, score_vector = evaluate_operator_on_all_datasets(operator, datasets)

            operator.score = avg_score
            operator.score_vector = score_vector

            population.append(operator)
            print(f"Operator {i+1}: Avg Score = {avg_score:.4f}, LOC = {operator.lines_of_code}")

        except Exception as e:
            print(f"Error generating operator {i+1}: {e}")
            continue

    if len(population) == 0:
        print("Failed to generate initial population!")
        return

    # Meta-evolution loop
    best_operator = max(population, key=lambda op: op.score)
    best_history = [best_operator.score]

    for gen in range(n_generations):
        print(f"\n=== Generation {gen+1}/{n_generations} ===")

        # Generate offspring
        offspring = []

        # Crossover
        print(f"Generating {n_crossover} offspring via crossover...")
        for i in range(n_crossover):
            try:
                # Semantic-aware selection
                parent_a, parent_b = semantics_aware_selection(population)
                print(f"  Crossover {i+1}: Parent A score={parent_a.score:.4f}, Parent B score={parent_b.score:.4f}")

                code = crossover_operators(client, parent_a, parent_b)
                operator = SelectionOperator(code)

                # Evaluate
                avg_score, score_vector = evaluate_operator_on_all_datasets(operator, datasets)
                operator.score = avg_score
                operator.score_vector = score_vector

                offspring.append(operator)
                print(f"  Offspring {i+1}: Score = {avg_score:.4f}, LOC = {operator.lines_of_code}")

            except Exception as e:
                print(f"Error in crossover {i+1}: {e}")
                continue

        # Mutation
        print(f"Generating {n_mutation} offspring via mutation...")
        elite = max(population, key=lambda op: op.score)

        for i in range(n_mutation):
            try:
                code = mutate_operator(client, elite)
                operator = SelectionOperator(code)

                # Evaluate
                avg_score, score_vector = evaluate_operator_on_all_datasets(operator, datasets)
                operator.score = avg_score
                operator.score_vector = score_vector

                offspring.append(operator)
                print(f"  Mutant {i+1}: Score = {avg_score:.4f}, LOC = {operator.lines_of_code}")

            except Exception as e:
                print(f"Error in mutation {i+1}: {e}")
                continue

        # Survival selection with bloat control
        if len(offspring) > 0:
            population = multi_objective_survival_selection(population, offspring, population_size)

        # Track best
        current_best = max(population, key=lambda op: op.score)
        if current_best.score > best_operator.score:
            best_operator = current_best

        best_history.append(best_operator.score)

        print(f"\nGeneration {gen+1} Summary:")
        print(f"  Best score: {best_operator.score:.4f}")
        print(f"  Best LOC: {best_operator.lines_of_code}")
        print(f"  Population size: {len(population)}")
        print(f"  Avg population score: {np.mean([op.score for op in population]):.4f}")
        print(f"  Avg population LOC: {np.mean([op.lines_of_code for op in population]):.1f}")

    # Save results
    print("\n=== Final Results ===")
    print(f"Best score: {best_operator.score:.4f}")
    print(f"Best score vector: {best_operator.score_vector}")
    print(f"Best LOC: {best_operator.lines_of_code}")
    print(f"\nBest operator code:")
    print("=" * 80)
    print(best_operator.code)
    print("=" * 80)

    # Save best operator to file
    with open("best_operator.py", "w") as f:
        f.write(best_operator.code)

    # Save history
    with open("best_history.json", "w") as f:
        json.dump({
            "best_history": best_history,
            "final_score": best_operator.score,
            "final_score_vector": best_operator.score_vector,
            "final_loc": best_operator.lines_of_code
        }, f, indent=2)

    print("\nResults saved to best_operator.py and best_history.json")

    return best_operator, best_history


if __name__ == "__main__":
    # Run with reduced settings for testing
    best_op, history = run_meta_evolution(
        n_generations=5,  # Small number for testing
        population_size=6,  # Small population
        n_crossover=4,
        n_mutation=1
    )
