#!/usr/bin/env python3
"""Estimate N=2000 PySR SLURM eval timing for new-style evolve_pysr.py runs.

In the new style, offspring batches are submitted to SLURM as each operator is
generated by the LLM (interleaved with offspring generation), then waited on
together. The multi-batch wait timer starts right after the LAST submission, so:

  T2 = elapsed since the LAST submission   (= "[timing] offspring evaluation")
  T1 = elapsed since the FIRST submission  (= T2 + offspring_generation_duration)

T1 here is an upper bound: it treats the first submission as if it happened at
the very start of offspring generation. The true first submission lands shortly
after the first LLM call returns, so the real T1 is somewhat smaller.

Filters:
- Wave size N = (#offspring batches in wave) × (tasks per batch) == 2000
- Driver: evolve_pysr.py new-style (detected via "Waiting on N offspring batches...")
- max_evals: 1_000_000 verified by reading one batch's tasks.json
"""
from __future__ import annotations

import json
import re
import statistics
from pathlib import Path

LOG_DIR = Path("out")
REPO_ROOT = Path.cwd()

GEN_BUNDLES_RE = re.compile(
    r"^Generated (\d+) offspring bundles \[timing: offspring generation (\d+)m ([0-9.]+)s\]"
)
GEN_TOTAL_RE = re.compile(
    r"\[timing\] generation total: (?:\d+)m (?:[0-9.]+)s "
    r"\(offspring gen (\d+)m ([0-9.]+)s, offspring eval (\d+)m ([0-9.]+)s\)"
)
WAITING_RE = re.compile(r"^Waiting on (\d+) offspring batches\.\.\.")
PYSR_EVAL_RE = re.compile(
    r"PySR SLURM eval: (\d+) tasks in batch (\S+) "
    r"\((\d+) configs x (\d+) datasets x (\d+) runs\)"
)
SCRIPT_RE = re.compile(r"\bScript: (.+)")


def to_seconds(m: int, s: float) -> float:
    return m * 60 + s


def normalize_path(text: str) -> Path:
    p = Path(text.strip())
    if p.exists():
        return p
    if "/meta_sr/" in str(text):
        suffix = str(text).split("/meta_sr/", 1)[1]
        candidate = REPO_ROOT / suffix
        if candidate.exists():
            return candidate
    return p


def verify_max_evals(tasks_json: Path) -> bool:
    if not tasks_json.exists():
        return False
    try:
        with tasks_json.open() as f:
            data = json.load(f)
        return all(int((t.get("pysr_kwargs") or {}).get("max_evals", -1)) == 1_000_000 for t in data)
    except Exception:
        return False


def find_relevant_logs() -> list[Path]:
    paths = []
    for p in sorted(LOG_DIR.glob("*.out")):
        if not p.stem.isdigit():
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        if "Waiting on " in text and "offspring batches..." in text:
            paths.append(p)
    return paths


def extract_waves(log_path: Path) -> list[dict]:
    """Walk the log and pull (offspring_count, tasks_per_batch, T1, T2) per wave."""
    lines = log_path.read_text(encoding="utf-8", errors="replace").splitlines()
    waves: list[dict] = []

    # Find every "Waiting on N offspring batches..." index.
    wait_idxs = [
        (i, int(m.group(1)))
        for i, line in enumerate(lines)
        if (m := WAITING_RE.match(line.strip()))
    ]

    for pos, (start, n_off) in enumerate(wait_idxs):
        # The wave runs from `start` to either the next "Waiting on..." or EOF.
        end = wait_idxs[pos + 1][0] if pos + 1 < len(wait_idxs) else len(lines)
        block = lines[start:end]

        # Pull the [timing] generation total breakdown for this generation.
        gen_total_match = None
        for line in block:
            gtm = GEN_TOTAL_RE.search(line)
            if gtm:
                gen_total_match = gtm
                break
        if not gen_total_match:
            continue
        offspring_gen_s = to_seconds(int(gen_total_match.group(1)), float(gen_total_match.group(2)))
        offspring_eval_s = to_seconds(int(gen_total_match.group(3)), float(gen_total_match.group(4)))

        # Pull tasks/batch from the first PySR SLURM eval in this block (or
        # immediately preceding lines, since some batches are submitted via
        # threadpool before the "Waiting on..." print).
        scan_lo = max(0, start - 200)
        eval_lines = [PYSR_EVAL_RE.search(l) for l in lines[scan_lo:end]]
        eval_lines = [m for m in eval_lines if m]
        if not eval_lines:
            continue
        # Last batch before the wait line is most representative.
        first_em = eval_lines[0]
        tasks_per_batch = int(first_em.group(1))
        n_total = n_off * tasks_per_batch

        # Verify max_evals via the first batch's tasks.json.
        script_text = None
        for line in lines[scan_lo:end]:
            sm = SCRIPT_RE.search(line)
            if sm:
                script_text = sm.group(1).strip()
                break
        ok_max = False
        if script_text:
            sp = normalize_path(script_text)
            if sp.exists():
                ok_max = verify_max_evals(sp.parent / "tasks.json")
        if not ok_max:
            continue

        waves.append(
            dict(
                line=start + 1,
                offspring=n_off,
                tasks_per_batch=tasks_per_batch,
                N=n_total,
                offspring_gen_s=offspring_gen_s,
                T2=offspring_eval_s,
                T1=offspring_eval_s + offspring_gen_s,
            )
        )

    return waves


def main() -> None:
    logs = find_relevant_logs()
    print(f"# Found {len(logs)} new-style logs with offspring waits")

    rows: list[dict] = []
    for log_path in logs:
        for wave in extract_waves(log_path):
            wave["slurm_id"] = log_path.stem
            rows.append(wave)

    n2000 = [r for r in rows if r["N"] == 2000]
    print(f"# Total waves found (any N): {len(rows)}")
    print(f"# Waves with N=2000:         {len(n2000)}")
    print()
    print("| slurm_id | line | offspring | per_batch | N | offspring_gen_s | T2_s | T1_s |")
    print("|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in sorted(n2000, key=lambda x: (int(x["slurm_id"]), x["line"])):
        print(
            f"| {r['slurm_id']} | {r['line']} | {r['offspring']} | "
            f"{r['tasks_per_batch']} | {r['N']} | {r['offspring_gen_s']:.1f} | "
            f"{r['T2']:.1f} | {r['T1']:.1f} |"
        )

    if n2000:
        t1s = [r["T1"] for r in n2000]
        t2s = [r["T2"] for r in n2000]
        print()
        print(f"N=2000 ({len(n2000)} waves)")
        print(f"  median T1 (since first submit): "
              f"{statistics.median(t1s):.1f}s = {statistics.median(t1s)/60:.1f} min")
        print(f"  median T2 (since last submit):  "
              f"{statistics.median(t2s):.1f}s = {statistics.median(t2s)/60:.1f} min")


if __name__ == "__main__":
    main()
